Multi db
mong/imongr pull request #110
Opened 2021-04-29 13:46 UTC by areedv

2021-04-29 17:15 UTC, areedv commented
![image](https://user-images.githubusercontent.com/1522857/116562937-e6f8e780-a903-11eb-89c1-a7baa6f9c8b0.png)
![image](https://user-images.githubusercontent.com/1522857/116563281-2de6dd00-a904-11eb-8a2e-c898b069dab1.png)
![image](https://user-images.githubusercontent.com/1522857/116563420-4ce56f00-a904-11eb-843d-15bac650b94d.png)

2021-04-29 20:25 UTC, arnfinn requested changes

2021-04-29 20:25 UTC, arnfinn commented on R/app_server.R
> +                      verify = "orange;'>Dataverifisering</h2>",
`</h3>`?

2021-04-29 20:25 UTC, arnfinn commented on R/server_output.R
> +                    verify = "orange;'>Dataverifisering</h2>",
`</h3>`?

2021-04-30 06:40 UTC, areedv commented on R/app_server.R
> +                       selected = "prod")
Har spekulert litt på om standard burde være prod eller verify. Men ja, vi kan prøve med verify som standard. Uansett, vi introduserer risiko med denne muligheten for valg av database: vi kommer helt sikkert til å oppleve innkonistente data. Og husk, informasjon om brukerrettigheter hentes bestandig fra prod slik oppsettet er nå. Altså, forvaltning av brukere må bestandig skje mot prod-databasen...

2021-04-30 06:48 UTC, areedv commented on R/getenv.R
> +    envvar <- "IMONGR_DB_HOST_QA"
Klart, og det må da settes opp 3 instanser av db (jeg har foreløpig bare testet med 2)

2021-04-30 08:55 UTC, areedv commented on R/server_output.R
> +                    verify = "orange;'>Dataverifisering</h2>",
Våkent!

2021-04-30 08:57 UTC, areedv commented on R/app_server.R
> +                      verify = "orange;'>Dataverifisering</h2>",
jepp...

2021-04-30 09:54 UTC, areedv commented on R/app_server.R
> +                       selected = "prod")
Utsetter denne litt da jeg trenger å se at oppsettet fungerer på aws først #111

2021-04-30 11:04 UTC, areedv commented on R/app_server.R
> +                       selected = "prod")
Ombestemte meg...

2021-04-30 11:05 UTC, areedv commented on R/getenv.R
> +    envvar <- "IMONGR_DB_HOST_QA"
Har også oppdatert imaget hnskde/imongr-dev slik at miljøvariablene er ferdig definerte

2021-04-30 13:02 UTC, merged