Issue 284 sk
mong/imongr pull request #299
Opened 2023-08-29 08:19 UTC by Stein-Kato

### Endringer i lokale databaser for testing

#### Legg til publish-tabell
`CREATE TABLE IF NOT EXISTS publish (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  md5_checksum CHAR(32) NOT NULL,
  terms_version VARCHAR(127) DEFAULT NULL,
  user_id SMALLINT UNSIGNED NOT NULL,
  registry_id SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT fk_publish_user
    FOREIGN KEY (user_id) REFERENCES user (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_publish_registry
    FOREIGN KEY (registry_id) REFERENCES registry (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;`

#### Endre delivery-tabell

`ALTER TABLE delivery DROP COLUMN latest;`
`ALTER TABLE delivery ADD publish_id SMALLINT UNSIGNED;`
`ALTER TABLE delivery ADD published BOOLEAN NOT NULL; `
`ALTER TABLE delivery ADD CONSTRAINT fk_delivery_publish
    FOREIGN KEY (publish_id) REFERENCES publish (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;`

#### Spesifikke endringer for verify og prod

I verify: 

`UPDATE delivery SET published = 1 
	WHERE NOT EXISTS(select 1 FROM data WHERE delivery.id = data.delivery_id);`

I prod: 

`UPDATE delivery SET published = 1;`

Ved første publisering til et register vil tidligere leveringer med kobling til data publiseres på nytt for gjeldende register slik at alle datoer oppdateres. 

### Endringer i funksjonalitet

Opplasting fungerer som før. `delivery`-tabellen får en ny linje der `publish_id` settes til `NULL` og `published` settes til 0. Når man trykker publiser hentes linjene fra `delivery`-tabellen der det finnes en kobling til data for gjeldende register og `publish` er lik 0. Deretter settes det inn en ny rad i `publish`-tabellen i verigy og prod, og det itereres over de filterte `delivery_id`-ene. Data kopieres fra `verify` til `prod` i bolker etter `delivery_id` slik at hver indikator får riktig dato for oppdatering i aggregeringen, og det lages en kobling mellom hver `delivery`-rad og tilhørende `publish`-rad. `terms_version` havner i `publish`-tabellen, men er beholdt i `delivery`-tabellen siden det ligger publiseringer der som man ønsker å ta vare på. 

`MD5_checksum`-kolonnen fungerer ikke flenger or å sjekke om data er duplikat av tidligere opplastinger og publiseringer. Checksummen var definert ulikt i ulike moduler, og splittingen av historikken i en `delivery`-tabell og en `publish`-tabell har ødelagt koblingenene mellom checksummene og duplikat-testen. Det bør defineres hva denne checksummen skal inneholde og hva man ønsker å sjekke den opp imot. 

### Endringer i tester

Det er lagt til en fil `test-publish.R` som simulerer tre brukere som gjør flere opplastinger til to registre for å teste at publiseringen fungerer som den skal. 

Disse testene er avhengig av tilgang til to testdatabaser `testdb_verify` og `testdb_prod`: 

`GRANT ALL PRIVILEGES ON 'testdb_verify'.* TO 'imongr'@'%' IDENTIFIED BY imongr;`
`GRANT ALL PRIVILEGES ON 'testdb_prod'.* TO 'imongr'@'%' IDENTIFIED BY imongr;`

2023-08-30 13:42 UTC, arnfinn commented on R/ops.R
>  duplicate_delivery <- function(pool, df, ind, registry) {
Kan denne slettes, sammen med `check_duplicate_delivery`?

2023-08-30 13:49 UTC, Stein-Kato commented on R/ops.R
>  duplicate_delivery <- function(pool, df, ind, registry) {
Burde gå greit hvis man også fjerner den fra config-fila.

2023-08-30 14:04 UTC, arnfinn requested changes

2023-08-30 14:05 UTC, arnfinn approved these changes

2023-08-31 07:15 UTC, Stein-Kato commented on R/ops.R
> +
Ordnet

2023-08-31 07:39 UTC, Stein-Kato commented on R/ops.R
>  duplicate_delivery <- function(pool, df, ind, registry) {
Har fjernet koden som hører til sjekken

2023-08-31 10:42 UTC, arnfinn approved these changes

2023-08-31 10:57 UTC, arnfinn commented
Jeg har nå endret databasen på aws

2023-08-31 11:12 UTC, merged